#################
# LEMP PLAYBOOK #
#################
---
- hosts: "all" 
  become: true 
  roles:   
  - mysql
  - nginx
  - php
  
  tasks:
  - name: "Reload nginx"
    ansible.builtin.service:
      name: "rh-nginx112-nginx"
      state: "reloaded"
