# NGINX
  - name: "Add epel-release repo" # Добавляем репозиторий
    yum:
      name: epel-release
      state: present

  - name: "Install nginx via yum"
    ansible.builtin.yum: 
      name: "nginx" # имя пакета для установки
      state: "latest" # установить последнюю версию пакета, в отличие от present, если пакет уже установлен в системе, попробует его обновить
      update_cache: true # вызвать yum update перед установкой, чтобы убедиться в наличии самой свежей базы данных о пакетах

  - name: "Delete /usr/share/nginx/html folder"
    ansible.builtin.file: # этот модуль работает с файлами и папками на удаленной машине
      path: "/usr/share/nginx/html" # путь к файлу/папке на удаленной машине
      state: "absent" # перевести папку в состояние absent - то есть удалить ее

  - name: "Copy our landing to /usr/share/nginx/html folder"
    ansible.builtin.copy: # этот модуль копирует файлы/директории с контрольной ноды на хосты
      src: "files/html" # путь к файлу/директории для копирования на контрольной ноде
      dest: "/usr/share/nginx/" # путь для вставки на удаленной машине
      owner: "nginx" # пользователь владелец файла/директории на удаленной машине
      group: "nginx" # группа владелец файла/директории на удаленной машине
      mode: "0644" # права доступа к файлу/директории

  
