---

- name: Install Software Collections
  yum:
    name: centos-release-scl
    state: installed

- name: Install MariaDB 10.2
  yum:
    name: rh-mariadb102
    state: installed    
    

- name: Enable MariaDB service
  systemd:
    name: rh-mariadb102-mariadb
    state: started
    enabled: yes
