 # PHP
  - name: "Installing php fpm and php mysql"
    ansible.builtin.yum:
      name: "{{ item }}" # здесь мы будем перечислять пакеты для установки, поэтому вместо имени здесь плейсхолдер
      state: "latest"
      update_cache: true
    with_items: # а вот тут уже и перечисляем, ansible сам их подcтавит вместо {{ name }}
      - "rh-php71-php-fpm"
      - "rh-php71-php-mysqlnd"

       

  - name: "Copy php files"
    ansible.builtin.copy:
      src: "files/test-php/www.conf" 
      dest: "/etc/opt/rh/rh-php71/php-fpm.d/www.conf"
      owner: "root"
      group: "root"
      mode: "0644"
   

  - name: Enable and Start php-fpm
    systemd:
      name: rh-php71-php-fpm
      enabled: yes
      state: started






